# Generated by Django 3.2.5 on 2021-07-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='num_aulas',
            field=models.IntegerField(null=True),
        ),
    ]
